import base64
import json
import os
import re
import smtplib
import tempfile
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from flask import Flask, jsonify, render_template, request
from werkzeug.utils import secure_filename

from doc_analyzer import analyze, save_report

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", "dev-only-change-in-prod")
app.config["MAX_CONTENT_LENGTH"] = 10 * 1024 * 1024  # 10 MB

ALLOWED_EXTENSIONS = {".pdf", ".txt", ".md"}
EMAIL_RE = re.compile(r"^[^@]+@[^@]+\.[^@]+$")


def allowed_ext(filename: str) -> bool:
    return Path(filename).suffix.lower() in ALLOWED_EXTENSIONS


def build_txt_report(filename: str, result: dict) -> str:
    lines = [
        f"ANALYSIS REPORT: {filename}",
        "Generated by doc_analyzer",
        "",
    ]
    sections = [
        ("SUMMARY", result.get("summary", "")),
        ("KEY DATA POINTS", result.get("key_data_points", [])),
        ("ACTION ITEMS", result.get("action_items", [])),
        ("RED FLAGS", result.get("red_flags", [])),
    ]
    for title, content in sections:
        lines.append(title)
        lines.append("-" * len(title))
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        else:
            lines.append(content)
        lines.append("")
    return "\n".join(lines)


def send_report_email(to_addr: str, filename: str, txt_report: str) -> None:
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))

    if not smtp_user or not smtp_pass:
        raise ValueError(
            "Email is not configured. Set SMTP_USER and SMTP_PASS environment variables."
        )

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = to_addr
    msg["Subject"] = f"Doc Analyzer Report: {filename}"

    msg.attach(MIMEText(
        "Your document analysis report is attached.\n\n"
        "Generated by Torres Tech Remote — Doc Analyzer",
        "plain",
    ))

    attachment = MIMEBase("application", "octet-stream")
    attachment.set_payload(txt_report.encode("utf-8"))
    encoders.encode_base64(attachment)
    stem = Path(filename).stem
    attachment.add_header(
        "Content-Disposition", f'attachment; filename="{stem}_report.txt"'
    )
    msg.attach(attachment)

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, to_addr, msg.as_string())


@app.route("/")
def index():
    return render_template("index.html", error=None)


@app.route("/analyze", methods=["POST"])
def analyze_file():
    def err(msg):
        return render_template("index.html", error=msg)

    f = request.files.get("file")
    if not f or f.filename == "":
        return err("Please select a file.")

    if not allowed_ext(f.filename):
        return err("Unsupported file type. Upload a PDF, TXT, or MD file.")

    filename = secure_filename(f.filename)

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            input_path = Path(tmpdir) / filename
            f.save(str(input_path))
            result = analyze(input_path)
            report_path = save_report(input_path, result)
            pdf_bytes = report_path.read_bytes()
    except SystemExit:
        return err("Analysis failed. Check that your file contains readable text and your API key is valid.")
    except Exception as e:
        return err(f"Unexpected error: {e}")

    stem = Path(filename).stem
    pdf_b64 = base64.b64encode(pdf_bytes).decode()
    txt_b64 = base64.b64encode(build_txt_report(filename, result).encode()).decode()
    result_b64 = base64.b64encode(json.dumps(result).encode()).decode()

    return render_template(
        "results.html",
        filename=filename,
        result=result,
        pdf_b64=pdf_b64,
        txt_b64=txt_b64,
        stem=stem,
        result_b64=result_b64,
    )


@app.route("/send-email", methods=["POST"])
def send_email_report():
    email_addr = request.form.get("email", "").strip()
    if not email_addr or not EMAIL_RE.match(email_addr):
        return jsonify({"ok": False, "error": "Please enter a valid email address."})

    try:
        result = json.loads(base64.b64decode(request.form.get("result_b64", "")).decode())
    except Exception:
        return jsonify({"ok": False, "error": "Invalid request data."})

    filename = request.form.get("filename", "document")
    txt_report = build_txt_report(filename, result)

    try:
        send_report_email(email_addr, filename, txt_report)
    except ValueError as e:
        return jsonify({"ok": False, "error": str(e)})
    except Exception as e:
        return jsonify({"ok": False, "error": f"Could not send email: {e}"})

    return jsonify({"ok": True})


if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
