import base64
import os
import tempfile
from pathlib import Path

from flask import Flask, render_template, request
from werkzeug.utils import secure_filename

from doc_analyzer import analyze, save_report

app = Flask(__name__)
app.secret_key = os.getenv("SECRET_KEY", "dev-only-change-in-prod")
app.config["MAX_CONTENT_LENGTH"] = 10 * 1024 * 1024  # 10 MB

ALLOWED_EXTENSIONS = {".pdf", ".txt", ".md"}


def allowed_ext(filename: str) -> bool:
    return Path(filename).suffix.lower() in ALLOWED_EXTENSIONS


def build_txt_report(filename: str, result: dict) -> str:
    lines = [
        f"ANALYSIS REPORT: {filename}",
        "Generated by doc_analyzer",
        "",
    ]
    sections = [
        ("SUMMARY", result.get("summary", "")),
        ("KEY DATA POINTS", result.get("key_data_points", [])),
        ("ACTION ITEMS", result.get("action_items", [])),
        ("RED FLAGS", result.get("red_flags", [])),
    ]
    for title, content in sections:
        lines.append(title)
        lines.append("-" * len(title))
        if isinstance(content, list):
            for item in content:
                lines.append(f"  - {item}")
        else:
            lines.append(content)
        lines.append("")
    return "\n".join(lines)


@app.route("/")
def index():
    return render_template("index.html", error=None)


@app.route("/analyze", methods=["POST"])
def analyze_file():
    def err(msg):
        return render_template("index.html", error=msg)

    f = request.files.get("file")
    if not f or f.filename == "":
        return err("Please select a file.")

    if not allowed_ext(f.filename):
        return err("Unsupported file type. Upload a PDF, TXT, or MD file.")

    filename = secure_filename(f.filename)

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            input_path = Path(tmpdir) / filename
            f.save(str(input_path))
            result = analyze(input_path)
            report_path = save_report(input_path, result)
            pdf_bytes = report_path.read_bytes()
    except SystemExit:
        return err("Analysis failed. Check that your file contains readable text and your API key is valid.")
    except Exception as e:
        return err(f"Unexpected error: {e}")

    stem = Path(filename).stem
    pdf_b64 = base64.b64encode(pdf_bytes).decode()
    txt_b64 = base64.b64encode(build_txt_report(filename, result).encode()).decode()

    return render_template(
        "results.html",
        filename=filename,
        result=result,
        pdf_b64=pdf_b64,
        txt_b64=txt_b64,
        stem=stem,
    )


if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
