#!/usr/bin/env python3
"""doc_analyzer — Analyze PDF and text files using the Claude API."""

import argparse
import json
import sys
from pathlib import Path

import anthropic
from dotenv import load_dotenv
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from rich.console import Console
from rich.panel import Panel

load_dotenv()

console = Console()

SUPPORTED_EXTENSIONS = {".pdf", ".txt", ".md"}

GREY_HEADER = HexColor("#D8D8D8")
LIGHT_RULE = HexColor("#BBBBBB")

SYSTEM_PROMPT = """\
You are a helpful document analyst. Analyze the provided document and return a JSON object with exactly these four keys:
- "summary": A 2-3 sentence overview of the document.
- "key_data_points": A list of important names, dates, amounts, or figures as bullet points.
- "action_items": A list of tasks, deadlines, or next steps. If none, return ["None identified."].
- "red_flags": A list of concerns, risks, or missing information. If none, return ["None identified."].

Return only valid JSON. No markdown fences, no extra text.
"""

header_style = ParagraphStyle(
    "SectionHeader",
    fontName="Helvetica-Bold",
    fontSize=11,
    textColor=black,
    spaceAfter=2,
)

body_style = ParagraphStyle(
    "Body",
    fontName="Helvetica",
    fontSize=10,
    textColor=black,
    leading=14,
    spaceAfter=4,
)


def read_file(path: Path) -> str:
    if path.suffix == ".pdf":
        return read_pdf(path)
    return path.read_text(encoding="utf-8")


def read_pdf(path: Path) -> str:
    try:
        import fitz
    except ImportError:
        console.print("[red]PyMuPDF not installed. Run: pip install pymupdf[/red]")
        sys.exit(1)

    doc = fitz.open(str(path))
    return "\n".join(page.get_text() for page in doc)


MODEL = "claude-sonnet-4-6"


def analyze(file_path: Path) -> dict:
    text = read_file(file_path)
    if not text.strip():
        console.print("[red]Could not extract any text from the file.[/red]")
        sys.exit(1)

    client = anthropic.Anthropic()

    with console.status(f"Analyzing with {MODEL}...", spinner="dots"):
        response = client.messages.create(
            model=MODEL,
            max_tokens=2048,
            system=[
                {
                    "type": "text",
                    "text": SYSTEM_PROMPT,
                    "cache_control": {"type": "ephemeral"},
                }
            ],
            messages=[
                {
                    "role": "user",
                    "content": f"Document: {file_path.name}\n\nContent:\n{text}",
                }
            ],
        )

    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    return json.loads(raw)


def print_section(title: str, content, border_style: str) -> None:
    if isinstance(content, list):
        body = "\n".join(f"• {item}" for item in content)
    else:
        body = content
    console.print(Panel(body, title=f"[bold]{title}[/bold]", border_style=border_style))


def build_section(title: str, content) -> list:
    header_para = Paragraph(title, header_style)
    header_table = Table([[header_para]], colWidths=[6.5 * inch])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GREY_HEADER),
        ("BOX", (0, 0), (-1, -1), 0.5, LIGHT_RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))

    elements = [header_table]

    if isinstance(content, list):
        for item in content:
            elements.append(Paragraph(f"• {item.lstrip('- ').strip()}", body_style))
    else:
        elements.append(Paragraph(content, body_style))

    elements.append(Spacer(1, 0.2 * inch))
    return elements


def save_report(input_path: Path, result: dict) -> Path:
    stem = input_path.stem
    output_path = input_path.parent / f"{stem}_report.pdf"

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=LETTER,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    title_style = ParagraphStyle(
        "Title",
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=black,
        spaceAfter=6,
    )
    sub_style = ParagraphStyle(
        "Sub",
        fontName="Helvetica",
        fontSize=9,
        textColor=HexColor("#666666"),
        spaceAfter=16,
    )

    story = [
        Paragraph(f"Analysis Report: {input_path.name}", title_style),
        Paragraph("Generated by doc_analyzer", sub_style),
    ]

    story += build_section("Summary", result.get("summary", ""))
    story += build_section("Key Data Points", result.get("key_data_points", []))
    story += build_section("Action Items", result.get("action_items", []))
    story += build_section("Red Flags", result.get("red_flags", []))

    doc.build(story)
    return output_path


def main():
    parser = argparse.ArgumentParser(
        description="Analyze PDF and text files using the Gemini API."
    )
    parser.add_argument("file", help="Path to a PDF or text file")
    args = parser.parse_args()

    path = Path(args.file)

    if not path.exists():
        console.print(f"[red]File not found: {path}[/red]")
        sys.exit(1)

    if path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        console.print(
            f"[red]Unsupported file type '{path.suffix}'. "
            f"Supported: {', '.join(sorted(SUPPORTED_EXTENSIONS))}[/red]"
        )
        sys.exit(1)

    console.print(Panel(f"[bold]{path.name}[/bold]", title="doc_analyzer"))

    result = analyze(path)

    print_section("Summary", result.get("summary", ""), "cyan")
    print_section("Key Data Points", result.get("key_data_points", []), "blue")
    print_section("Action Items", result.get("action_items", []), "yellow")
    print_section("Red Flags", result.get("red_flags", []), "red")

    report_path = save_report(path, result)
    console.print(f"\n[green]Report saved:[/green] {report_path}")


if __name__ == "__main__":
    main()
